### ISSUE TITLE
An error occurred in the build for AX620E.

### ISSUE THREAD

**Issue by nnn112358** [ml-inory/melotts.axera#3]
Thank you for the very innovative repository.
When I tried to build for AX620E, an error occurred. I tried building for AX650 and it was successful.

If you have any means of accommodating this, please let us know. 
Or, are there any plans to support AX620E in the future?

```
$ pulsar2 build --input decoder-zh.onnx --config config_decoder_u16.json --output_dir decoder --output_name decoder.axmodel --target_hardware AX620E --npu_mode NPU1 --compiler.check 0

Traceback (most recent call last):
  File "</opt/pulsar2/yamain/main.py>", line 4, in <module>
  File "<frozen yamain.main>", line 329, in <module>
  File "<frozen yamain.main>", line 257, in pulsar2
  File "<frozen yamain.main>", line 152, in wrapper
  File "<frozen yamain.common.error>", line 23, in wrapper
  File "<frozen yamain.command.build>", line 105, in build_error
  File "<frozen yamain.common.error>", line 14, in wrapper
  File "<frozen yamain.command.build>", line 507, in build
  File "<frozen yamain.command.build>", line 1172, in compile_ptq_model
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "<frozen yamain.common.error>", line 61, in guard_context
  File "<frozen yamain.common.error>", line 73, in error_func
yamain.common.error.CodeException: (<ErrorCode.NPUBackendError: 8>, AssertionError('ocm alloc with ddr_swap failed'))
````

All logs are here.
https://gist.github.com/nnn112358/1c88ace6c17aeaf5b3cdb08aff656b1e

**Comment by ml-inory** [comment]
Yes, we came into the same issue building for AX620E and we will let you know once we fixed it.

**Comment by nnn112358** [comment]
I see. I look forward to future enhancements.

**Comment by nnn112358** [comment]
I have successfully converted with the new Pulsar2 Version and NPU Mode to NPU2.
In NPU Mode, NPU1 gives an error (logs are below); NPU2 succeeds.
Pulsar2 Version versions 3.2-temp-melotts (93dc9c99) and 3.3 (3cdead5e) succeed.


| target_hardware | Pulsar2 Version | NPU Mode | Status |
|----------------|---------|-----|--------|
| AX620E| 3.2-temp-melotts(93dc9c99) | NPU1 | Error |
| | | NPU2 | Success |
| | 3.3(3cdead5e) | NPU1 | Error |
| | | NPU2 | Success |
| | 3.3-temp(temp-f0b32d03) | NPU2 | Error |

However, melotts conversion in Pulsar2 requires a large memory. I needed up to 20GB for ax conversion.
If memory is low, “killed” will occur during the process.

<img width="326" alt="image" src="https://github.com/user-attachments/assets/476fd53c-0128-4dc9-93ee-e1f9303a7578" />



### 3.2-temp-melotts(93dc9c99) & NPU1

```
['op_11:pre_transpose_out[:1,:1024,:256]777_s0_gop', 'op_11:AxQuantizedConv_777_s0_gop_extra_op3_AxQuantizedConv_op0_pad_t_r']
op_11:AxQuantizedConv_777_s0_gop_extra_op3_AxQuantizedConv_op0_pad_t_r
[524288, 140288]
140288
['op_11:pre_transpose_out[:1,:1024,:256]777_s0_gop_1_', 'op_11:AxQuantizedConv_777_s0_gop_extra_op0_AxQuantizedConv_op0_pad_t_r_1_']
add ddr swap... ⠼ ━━━━━╸                                                                            20874/296613 0:00:05
Traceback (most recent call last):
  File "<frozen yamain.common.error>", line 59, in guard_context
  File "<frozen yamain.command.build>", line 1162, in compile_ptq_model
  File "<frozen yamain.command.build>", line 1359, in compile_npu_subgraph
  File "<frozen yasched.test_onepass>", line 3263, in test_onepass_ir
  File "<frozen yasched.test_onepass>", line 3240, in build
  File "<frozen yasched.test_onepass>", line 3386, in graph2models
  File "<frozen yasched.test_onepass>", line 2526, in results2model
  File "<frozen yasched.test_onepass>", line 1891, in ocm_allocate_and_ddr_swap
  File "<frozen yasched.test_onepass>", line 1820, in try_alloc
AssertionError: ocm alloc with ddr_swap failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "</opt/pulsar2/yamain/main.py>", line 4, in <module>
  File "<frozen yamain.main>", line 329, in <module>
  File "<frozen yamain.main>", line 257, in pulsar2
  File "<frozen yamain.main>", line 152, in wrapper
  File "<frozen yamain.common.error>", line 23, in wrapper
  File "<frozen yamain.command.build>", line 217, in build_error
  File "<frozen yamain.common.error>", line 14, in wrapper
  File "<frozen yamain.command.build>", line 595, in build
  File "<frozen yamain.command.build>", line 1164, in compile_ptq_model
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "<frozen yamain.common.error>", line 61, in guard_context
  File "<frozen yamain.common.error>", line 73, in error_func
yamain.common.error.CodeException: (<ErrorCode.NPUBackendError: 8>, AssertionError('ocm alloc with ddr_swap failed'))
```

### 3.3-temp(temp-f0b32d03)&  NPU2
```
['op_52:pre_transpose_out[:1,:8192,:128]1060_s0_gop_1_', 'op_64:AxQuantizedConv_1060_s7_gop_extra_op0_AxQuantizedConv_op0_pad_op0_pad_op0_pad_op1_pad_op0_pad_t_r']
op_52:pre_transpose_out[:1,:8192,:128]1060_s0_gop_1_
[2097152, 65760]
2097152
['op_64:AxQuantizedConv_1060_s7_gop_extra_op0_AxQuantizedConv_op0_pad_t_r_1_', 'op_64:AxQuantizedConv_1060_s7_gop_extra_op1_AxQuantizedConv_op0_pad_t_r_1_']
add ddr swap... ⠼ ━━━━━━━━━━━━━━━━━━━━━━━━                                                          81746/270373 0:00:31
Traceback (most recent call last):
  File "<frozen yamain.common.error>", line 59, in guard_context
  File "<frozen yamain.command.build>", line 1171, in compile_ptq_model
  File "<frozen yamain.command.npu_backend_compiler>", line 199, in compile
  File "<frozen yasched.test_onepass>", line 3272, in test_onepass_ir
  File "<frozen yasched.test_onepass>", line 3256, in build
  File "<frozen yasched.test_onepass>", line 3402, in graph2models
  File "<frozen yasched.test_onepass>", line 2539, in results2model
  File "<frozen yasched.test_onepass>", line 1862, in ocm_allocate_and_ddr_swap
  File "<frozen yasched.test_onepass>", line 1833, in try_alloc
AssertionError: ocm alloc with ddr_swap failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "</opt/pulsar2/yamain/main.py>", line 4, in <module>
  File "<frozen yamain.main>", line 335, in <module>
  File "<frozen yamain.main>", line 263, in pulsar2
  File "<frozen yamain.main>", line 158, in wrapper
  File "<frozen yamain.common.error>", line 23, in wrapper
  File "<frozen yamain.command.build>", line 105, in build_error
  File "<frozen yamain.common.error>", line 14, in wrapper
  File "<frozen yamain.command.build>", line 509, in build
  File "<frozen yamain.command.build>", line 1174, in compile_ptq_model
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "<frozen yamain.common.error>", line 61, in guard_context
  File "<frozen yamain.common.error>", line 73, in error_func
yamain.common.error.CodeException: (<ErrorCode.NPUBackendError: 8>, AssertionError('ocm alloc with ddr_swap failed'))

```
